[master]
  runner = "s3://ambiata-dispensary-v2/dist/branches/master-haskell/linux/x86_64/20170104093638-a10cd6e/master-haskell-20170104093638-a10cd6e"
  version = 1
  sha1 = "3b707a2ba2d74ee13fe81a658bed191a5808e6f5"

[build.dist-7-8]
  GHC_VERSION="7.8.4"
  CABAL_VERSION="1.22.4.0"
  MAFIA_HAPPY = "true"

[build.dist-7-10]
  GHC_VERSION="7.10.2"
  CABAL_VERSION="1.22.4.0"
  MAFIA_HAPPY = "true"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "mafia"

[build.dist-8-0]
  GHC_VERSION="8.0.1"
  CABAL_VERSION="1.24.0.0"
  MAFIA_HAPPY = "true"

[build.branches-7-8]
  GHC_VERSION = "7.8.4"
  CABAL_VERSION = "1.22.4.0"
  MAFIA_HAPPY = "true"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  MAFIA_HAPPY = "true"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "mafia"

[build.branches-8-0]
  GHC_VERSION="8.0.1"
  CABAL_VERSION="1.24.0.0"
  MAFIA_HAPPY = "true"
